name: Daily Email Cron

on:
  schedule:
    - cron: '* * * * *'  # Ejecutar cada minuto para pruebas
  workflow_dispatch:  # Permite ejecución manual desde GitHub

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Usa una versión de Node.js reciente

    - name: Clean and Install dependencies
      run: |
        rm -rf node_modules
        rm package-lock.json
        npm install

    - name: Run cron job
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
      run: node src/cronServer.js
